apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-svc
spec: 
  selector:
    matchLabels:
      env: test
  replicas: 2
  template:
    metadata:
      name: deploy-svc-pod
      labels: 
        env: test        
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80    

---

apiVersion: v1 
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort 
  selector:
    env: test
  ports:
  - port: 80
    targetport: 80  
