apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sb-web-deploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
       app: sb-web-app
       version: v1    
       color: blue
  template:
    metadata:
      name: sb-web-deploy-pod
      labels:
        app: sb-web-app
        version: v1    
        color: blue 
    spec:
      containers:
      - name: sb-web-deploy-container
        image: rchalapathi/logger-efk:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1 
kind: Service
metadata:
  name: sb-web-svc
spec:
  type: LoadBalancer
  selector:
    app: sb-web-app
  ports:
  - port: 80
    targetPort: 8080  